### ISSUE TITLE
Audit Windows functions for deprecated calls

### ISSUE THREAD

**Issue by shane-kerr** [shane-kerr/Mintcoin-Desktop-Wallet#12]
While trying to figure out what the data directory is in Windows, I discovered that the function used to get the default data directory is deprecated. It uses the [SHGetSpecialFolderPathA()](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762204(v=vs.85).aspx) function which has not been supported since Windows 2000, which was declared end-of-life by Microsoft in 2010, almost 4 years before the MintCoin project started!

Probably there are more deprecated functions in use. We should find these and update them to something more modern. (Probably targeting Windows 7 is a reasonable approach.)

**Comment by waraileron** [comment]
No other deprecated windows functions found in
allocators.h, compat.h, netbase.h, net.h, util.h, crypter.cpp, db.cpp, init.cpp, netbase.cpp, net.cpp, protocol.cpp, txdb-bdb.cpp, util.cpp

**Comment by shane-kerr** [comment]
Thanks for the audit! I've created a new ticket which covers the only function that needs to be fixed.
