### ISSUE TITLE
assertion failed on armhf daemon

### ISSUE THREAD

**Issue by nexus166** [shane-kerr/Mintcoin-Desktop-Wallet#16]
right at mintcoind start

> mintcoind: kernel.cpp:422: unsigned int GetStakeModifierChecksum(const CBlockIndex*): Assertion `pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)' failed.

**Comment by shane-kerr** [comment]
Can you give a little more detail about this system? Also, were you starting from an empty startup or were you using the blockchain downloaded from some other system?
